### ISSUE TITLE
Create v0.3 and include bugs fixes in flame_oxygen

### ISSUE THREAD

**Issue by freewheelnat** [flame-engine/oxygen#18]
A couple of bugs were fixed a few months ago but no new release was created. v0.2 dates from before the [bugs fix PR](https://github.com/flame-engine/oxygen/pull/13). That PR fixes the bug with removing components from entities, which is very important (it's a blocker for any game not to have it).

To use it, we need to do following:

```
dependency_overrides:
  oxygen:
    git:
      url: https://github.com/flame-engine/oxygen.git
```

And, additionally, we also need to amend [FlameWorld](https://github.com/flame-engine/flame/blob/main/packages/flame_oxygen/lib/src/flame_world.dart) by adding `entityManager.processRemovedComponents();` to its `update` method.

It would be super useful if you could create a new release for oxygen, and then do the quick change to flame_oxygen.
